spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop_app_db
    username: postgres
    password: password
  mail:
    enabled: false
    host: smtp.gmail.com
    port: 587
    username: SECRET
    password: SECRET
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: shopApp
      port: 27017
      host: 127.0.0.1
      auto-index-creation: true

app:
  cache:
    spec: maximumSize=500,expireAfterAccess=600s
jwt:
  expiration: 3h
